### ISSUE TITLE
add `-l` argument for printing list of repositories

### ISSUE THREAD

**Issue by kra53n** [kra53n/getgit#15]

**Comment by slimkaki** [comment]
Hello! Can I be assign to this issue?

**Comment by kra53n** [comment]
@slimkaki
Hello, of course!

**Comment by slimkaki** [comment]
@kra53n Sorry for the late response. I had some trouble making it work, but I finally did and already opened a PR! Reach me if it is still needed! 
PR Link: https://github.com/kra53n/getgit/pull/16

**Comment by kra53n** [comment]
Hi @slimkaki!

Everything is good but I want to make another thing.

I want make printing a list of repositories like when you just run `getgit` with only differs that it will not display any excess new lines and numbers. E.g.:

```
getgit
asteroids
anothre_repo
```

It's even easier to do.

To store cloned repositories is a slightly strange idea. If user delete repo it will still be in the `.repos` file.

Concerning of

> the late response

never mind. You are doing this work with enthusiasm and I am appreciate it.
